feat: Added product and order page
Thirumathikart/thirumathikart-seller pull request #10
Opened 2022-11-04 07:19 UTC by mithmusq3

Two different Product Models have been taken while rebasing (should resolve),
Creating this Pr to build and present

2022-11-04 18:02 UTC, Ram-20062003 requested changes

2022-11-04 18:02 UTC, Ram-20062003 commented on lib/views/order_page.dart
> +      ordersController.copy(ordersListMain);
use of copy here?

2022-11-04 18:03 UTC, Ram-20062003 commented
Pull rebase your PR

2022-11-05 09:53 UTC, mithmusq3 commented
Requested Changes has been addressed

2022-11-05 10:43 UTC, Ram-20062003 requested changes

2022-11-05 10:43 UTC, Ram-20062003 commented on lib/views/product_page.dart
> +                          height: 180 >
this if conditon is not needed ig

2022-12-18 05:14 UTC, merged